### ISSUE TITLE
Filtering with regexp not working?

### ISSUE THREAD

**Issue by dw72** [Kurounin/Pagination#2]
I use your package, and it works almost fine because have a problem with filtering using RegExp.
```javascript
    const yearFilter = {
        year: year,
    };
    
    const searchFilter = search ? {
      $or: [
        {'paragraph.symbol': new RegExp(search)},
      ],
    } : {};

    const filter = _.extend({}, yearFilter, searchFilter);

    Template.instance().pagination.filters(filter);
```
This without RegExp (code below) works ok.
```javascript
    const yearFilter = {
        year: year,
    };
    
    const searchFilter = search ? {
      $or: [
        {'paragraph.symbol': search},
      ],
    } : {};

    const filter = _.extend({}, yearFilter, searchFilter);

    Template.instance().pagination.filters(filter);
```
I used earlier filters with RegExp on normal publication and it was ok as well.

**Comment by dw72** [comment]
Now I code to 
```javascript
    const searchExp = '.*(' + search + ').*';
    const searchFilter = search ? {
      $or: [
        {'paragraph.symbol': {$regex: searchExp}},
      ],
    } : {};
```
and it working but is strange why using RegExp object not working

**Comment by Kurounin** [comment]
`'paragraph.symbol': new RegExp(search)` does not work, because `pagination.filters()` accepts the filters in mongodb format. The correct mongodb format is, like you discovered, `'paragraph.symbol': { $regex: search, $options: "i"}`

You can find more info here: https://docs.mongodb.org/manual/reference/operator/query/regex/
