### ISSUE TITLE
Is it possible to define a sorting with relevance algorithm

### ISSUE THREAD

**Issue by boboci9** [Kurounin/Pagination#26]
Hi, is it possible to define somehow a sorting algorithm where I can define different sorting weights based on some conditions even regex maybe, so I can influence what elements to show up first in the result? 

Btw, the package is super extraordinary, it works great and fast with large collections, great work !!!

**Comment by Kurounin** [comment]
Hi,

Glad you like the package.
To be able to sort by relevance in mongodb, you would have to use an aggregation query, instead of a find (take a look at http://stackoverflow.com/questions/23641752/mongodb-sort-by-relevance ), in which case a lot of additional params are required (you would even need to define every field that you want to retrieve) and a different implementation on the server side.
I do not have the time to implement something like this now and don't know how used this feature would be, but if you want to try and tackle this problem I can take a look over the PR.

**Comment by Kurounin** [comment]
You could also try and see if assigning weights to specific fields, by creating a manual index can suit your needs: https://docs.mongodb.com/v3.2/tutorial/control-results-of-text-search/

**Comment by boboci9** [comment]
Thanks, I will get back to you on what I find.
