### ISSUE TITLE
Meteor.Pagination constructor violates ESLint rule no-new

### ISSUE THREAD

**Issue by mgscreativa** [Kurounin/Pagination#46]
Hi! In order to use Meteor.Pagination I have to define it as this

```
new Meteor.Pagination(Activities, {
  name: 'activities.paginatedList',
  /* filters: { owner: userId },*/
  dynamic_filters: function activitiesDynamicFilters() {
    if (isAdmin(this.userId)) return {};

    return { owner: this.userId };
  },
  transform_options: (filters, options) => {
    const newOptions = options;
    const fields = {
      title: 1,
      body: 1,
      owner: 1,
    };

    newOptions.fields = _.extend(fields, newOptions.fields);

    return newOptions;
  },
});
```
This definition violates ESLint rule no-new http://eslint.org/docs/rules/no-new

Is it possible to avoid that ESLint message without disabling the rule? Or is it possible to define the pagination otherwise?

Thanks!

**Comment by Kurounin** [comment]
Hi,

You can assign the returned instance to an object, in order to avoid the error.
`const activityPagination = new Meteor.Pagination(Activities, {...});`

**Comment by mgscreativa** [comment]
Yep, but that’s generate another ESLint hint **no-unused-vars**

**Comment by Kurounin** [comment]
Any error for ESLint can be suppressed using a comment like
`// eslint-disable-next-line no-new`

Since the usage of a class had no use on server-side I published a new version which deprecates the usage of the `Meteor.Pagination` class on server-side, in favor of the `publishPagination` function.

To be able to use it you need to import it in your server-side file using the following statement:
`import { publishPagination } from 'meteor/kurounin:pagination';`

**Comment by mgscreativa** [comment]
Great! many thanks!
