### ISSUE TITLE
Text search query not retrieving score

### ISSUE THREAD

**Issue by carlosalvidrez** [Kurounin/Pagination#64]
Hi guys, is there a way to retrieve the result of a text search? I get the results, but not the score, so I can't order by match relevance. 
Thanks!

**Comment by Kurounin** [comment]
Hi,

In order to retrieve the score of a text search, you need to ensure you did the following things:
- on server side define a _text index_
- on server side when you publish the pagination, add to _options.fields_ the _score_, using `transform_options` method

For an exact implementation check this commit https://github.com/Kurounin/PaginationExample/commit/c0941679b7b1f88483547f1d8e9da42804bef90b
