### ISSUE TITLE
any example about paginate in app separate

### ISSUE THREAD

**Issue by tritrul** [Kurounin/Pagination#76]
hello, i want to paginate some collections but i have 2 app, ui and backend, publish its in backend and subscription in ui.
anybody can help me???
thanks

**Comment by Kurounin** [comment]
If you have 2 separate meteor applications running a different code, why not make another publication in the UI application?
In order to use the same server side publication from Backend app in UI app, you would need to have a websocket connection on the client side UI app to Backend server side app, but this is something out of the scope of the current package and would better be posted in the meteor forum.

**Comment by Kurounin** [comment]
Exactly which previous version works? I don't remember having a condition to wait for ddpconnection, since Meteor is handling it automatically.

**Comment by tritrul** [comment]
please see in on the client/pagination.js, the constructor receive (collection, filters, ddpconnection) if (ddpconnection){something} else {otherthings}.
well, i just did a new version do you want to see it for inclusion in your news version????
thanks

**Comment by Kurounin** [comment]
Sure, if you can do a PR I'll take a look at the changes and include them.

**Comment by Kurounin** [comment]
I published a new version which allows specifying a connection when instantiating the client side pagination:
```javascript
Template.myList.onCreated(function () {
    this.pagination = new Meteor.Pagination(MyCollection, {
        connection: ServerDdpConnection
    });
});
```
