### ISSUE TITLE
I want to  concatenate/transform the doc before publishing 

### ISSUE THREAD

**Issue by varunlakshmaiah** [Kurounin/Pagination#85]
Hi I want to to modify the doc before publishing how can I achieve this.... How to use transform function in find() before publishing using your publishPagination(); function as I can see.. you can only pass 
query and filters only..

Thank You

**Comment by Kurounin** [comment]
Currently there's no way to modify the document on server side before publishing it to client side. Why do you need to that? Can't you create a function to process the document on client side and get the same functionality?

**Comment by varunlakshmaiah** [comment]
Hi Thanks for the reply..

I am stuck in this case :

I have two collections Projects and Settings

Projects Doc structure 
{
    name:"abc",
    description:"skldfjlskdjflksj"
    settings:"xvksfhyyyswwwjjjj",
    owner:"sfsdfsdfscxcvbvbc",
}

Settings Doc structure

{
    _id:"xvksfhyyyswwwjjjj",
    type:"a",
    class:"1"    
}


I want final structure like this before subscribing so that I can directly pass this to blaze helper 

{
    name:"abc",
    description:"skldfjlskdjflksj"
    settings:{
    type:"a",
    class:"1"    
},
    owner:"sfsdfsdfscxcvbvbc",
}

I know I can concatenate using array functions but how can I  paginate array using your library (Since your library accepts only Collection or subscription name)

Now the problem is I want to display a list of projects using pagination , But I can only pass the collection name to your library for pagination

* Also I want to list projects based on type for example if user selects type "a" I should be able to show paginated list of all projects with type "a" only and viceversa

* I'm also doing a search by project name.

So My point is how can I achieve Searching,List based on type ,and pagination by combining multiple collection using your library

Thank You

**Comment by varunlakshmaiah** [comment]
Also is there any way to paginate the data coming from already existing publication..?? like without using publishPagination(MyCollection) on server..??

**Comment by Kurounin** [comment]
You can not use the client side pagination using existing publications, since the server side publishPagination() is needed to perform the actual pagination on server side.

Regarding your specific use case, it seems you are trying to use mongo as a relational database and it wasn't built for that, hence it doesn't support joining 2 collections based on a column and searching for other columns present either on one collection or the other.

What you are trying to achieve could be done in 2 steps:
- search & retrieve all **Settings** of type `a`
- paginate the **Projects** using as filter for column `settings` the `_id` retrieved in previous step

**Comment by varunlakshmaiah** [comment]
@Kurounin Thank You for your reply.. I am working on route based pagination
